<div id="content">
		<div id="maincolumn">
			<a name="startcontent" id="startcontent"></a>
			<!-- test comment from template -->
<h1>All Children Can Write</h1>
<p>By: Donald H.  Graves</p><a name="anchor916482"></a>

<p>The following article by Donald Graves, considered by many to be the &quot;father&quot; of the process approach to writing, is a classic piece on the need for a change in the way writing has typically been taught in schools. This article helped spark the movement now known as the &quot;Writer's Workshop&quot; approach.</p>
<p>We selected this article because Graves discusses the challenges and needs of students with learning disabilities in the area of writing, clearly lays out how teachers can establish a community of learners and the writing process, and provides examples of teachers and students working together. We recommend the Writers' Workshop approach as a basis for teaching writing to students with learning disabilities, in combination with explicit instruction in writing strategies and skills.</p>
<p>Many children who have learning disabilities are poor writers. They equate their struggles with handwriting, spelling, and language conventions with a lack of ideas and information worth sharing. The writing-process approach to teaching first emphasizes what children know, then the conventions that will help them share their meaning with others in the class. This approach has led to major breakthroughs for young writers, particularly those who have learning problems.</p>
<p>This article reexamines writing as communication for oneself and for other audiences. This process occurs in classrooms where children see how teachers demonstrate their own learning in the midst of a highly structured environment.</p>
<p>Four essentials to a successful writing-process program are described: the adequate provision of time (at least 4 days per week), child choice of writing topic, response to child meaning, and the establishment of a community of learners.</p>
<p>Continued success in teaching writing depends on teacher's work with their own writing. Study programs, as well as additional reading materials, are suggested.</p>
<p>I stood at the side of Ms. Richards' third grade classroom watching the children write. We were at the beginning of our 2-year National Institute of Education study of children's composing processes. The school had diagnosed two of the children in Ms. Richards' room as having severe visual-motor problems. They were not hard to find.</p>
<p>Both leaned over their papers, their elbows crooked at right angles to their bodies to protect the appearance of their papers. I walked over to take a closer look at one of the two children's papers. Billy's paper was smudged, wrinkled, letters blackened; in several instances, his paper was thinned and blackened still more where he had gone through several spelling trials on the same work. The more serious aspect of Billy's writing profile was not his visual-motor difficulty, the appearance of his paper, or his numerous misspellings. Billy was a self-diagnosed poor writer. He connected his writing problems with a lack of worthwhile ideas and experiences. In addition, he was well-versed in what he couldn't do.</p>
<p>Billy had been in a separate program emphasizing visual-motor skills, letter formation, and various fine-motor tasks. No question, using a pencil was painful and arduous for him. Teachers complained that Billy rarely completed his work and was constantly behind the others, though he seemed to be articulate. Billy's program was skill-based, disconnected from meaning, and filled with positive reinforcement about his ability to form letters on good days. There was not attempt to connect his writing with the communication of ideas.</p>
<p>Children with learning disabilities often work on skills in isolation, disconnected from learning itself, and therefore disconnected from themselves as persons. Therefore, like Billy, though their skills may improve slightly in isolation, the children do not perceive the function of the skill. Worse, they do not see the skill as a means to show what they know. Skills work merely supplies additional evidence for the misconception that they are less intelligent than other children.</p>
<p>Billy was in a classroom that stressed writing as a process. This meant the children received help from the time they chose a topic to the time they completed their final work. Ms. Richards played the believing game, starting with what Billy knew, particularly his experiences. In fact, Billy's breakthrough as a writer came when his teacher discovered his interest in and knowledge of gardening. As Ms. Richards helped him to teach her about this subject, she learned how to plant, cultivate, water, fertilize, and provide special care for certain varieties of tomatoes. Although Billy wrote more slowly than the other children, he became lost in his subject, forgot about his poor spelling and handwriting, ceased to cover his paper, and wrote a piece filled with solid information about gardening. Once Billy connected writing with knowing-his knowing- it was then possible to work with his visual motor and spelling problems, but as incidental to communicating information.</p>
<p>Ms. Richards is now one of the thousands of teachers who teach writing as a process in the United States and the English speaking world. New research and publications, university courses, and numerous summer institutes, are now helping teachers and administrators to find out for themselves what students can do when they focus on the meaning of their writing. Much of the focus of these institutes and courses is on the teachers' own writings: most of us had to rediscover the power of writing for ourselves before we could learn to hear what these young writers had to teach us.</p>
<p>Although writing-process work helps all writers, it seems to be particularly successful with people who see themselves as disenfranchised from literacy. I place in this group learners like Billy who have diagnosed learning disabilities and the accompanying &quot;I-don't-know-anything&quot; syndrome.</p>
<p>The writing-process approach to teaching focuses on children's ideas and helps children teach the teacher or other children in the class what they know, with emphasis first given to ideas and clarifying. This is the first experience many children have with other humans who work hard to point to what they know, instead of what is lacking in the message. Small wonder then that the writing process works best with the disenfranchised, who become a bit giddy at the prospect of seeing their words on paper affecting the thinking of others.</p>
<p>Understanding writing as communication is the heart of teaching the writing process. This article will first focus on the nature of writing, look in greater detail at research on the writing process itself, examine two principles in teaching writing, and then describe four basics in establishing a writing program. It also has a brief section on further reading and recommendations for summer programs for people interested in continuing their study of the writing process.</p>
<p><a href="article/6204#anchor916482">Top of Page</a></p>
<h2>What is writing?</h2>
<p>Writing is a medium with which people communicate with themselves and with others at other places and times. When I write, I write to learn what I know because I don't know fully what I mean until I order the words on paper. Then I see ... and know. Writers' first attempts to make sense are crude, rough approximations of what they mean. Writing makes sense of things for oneself, then for others.</p>
<p>Children can share their writing with others by reading aloud, by chatting with friends while writing, or (in more permanent form) by publishing. Billy found that writing carried a different authority from spoken words. When he took the gardening piece out in December, he found that words written in September could be savored 3 months later. Furthermore, when he read the published books of other children in his room, he began to realize that his book on gardening was read by others when he wasn't present.</p>
<p>Written language is different from oral language. When Billy speaks, he reinforces his meaning by repeating words and phrases. Unlike when he writes, an audience is present; when the audience wanders or indicates disagreement, he changes his message with words, hand signals, facial expressions, and body posture. This is the luxury of oral discourse. &quot;Error,&quot; adjustment, and experimentation are an expected part of oral discourse.</p>
<p>There is a different tradition surrounding most teaching of writing. Only one attempt, one draft is allowed to communicate full meaning (without an audience response). Red-lined first drafts are the norm; we blanch at any misspellings or crudely formed letters.</p>
<p>Still worse, writing has been used as a form of punishment: &quot;Write your misspelled worry 25 times.&quot; (This is called reinforcement of visual-memory systems.); &quot;Write one hundred times, I will not chew gum in school&quot;', &quot;Write a 300 word composition on how you will improve your attitude toward school.&quot; Most teachers teaching in 1985 were bathed in the punishment syndrome when they were learning to write. Small wonder that most of us subtly communicate writing as a form of punishment. We have known no other model of teaching.</p>
<h2>The writing process</h2>
<p>When children use a meaning-centered approach to writing, they compose in idiosyncratic ways. Each child's approach to composing is different from the next. Some draw first, write two words, and in 10 minutes or less announce, &quot;I'm done.&quot; Others draw after writing or do not write at all; instead, they speak with a neighbor about what they will write. Some stare out the window or at the blank page and write slowly after 20 minutes of reflection. At some point in their development, writers believe one picture and two words beneath the drawing contain an entire story. In the writer's mind, the story is complete; members of the audience shake their heads and try to work from drawing to text and back to understand the author's intent.</p>
<p>Such idiosyncratic approaches by children seem capricious to outsiders, confusing to children, and bewildering to us as teachers. We intervene with story starters to &quot;get them going,&quot; produce pictures as stimuli for writing, and consult language arts texts for language activities. The texts provide &quot;systematic&quot; approaches, often through the teaching of the sentence, advance to two sentences, and finally development of the paragraph. Our detailed observation of young children writing shows they simply don't learn that way. Rather, they write three sentences in one in their first year, not understanding where one sentence ends and the other begins. Studies of children's understanding and use of sentences show they don't acquire full sentence sense until much later (about fifth grade).</p>
<p>The most pernicious aspect of teacher interventions is that children begin to learn early on that others need to supply topics because they come to the page with nothing in their heads. A focus on skills and form to the exclusion of child initiated meaning further confirms their lack of fit with the writing process.</p>
<p>Prepared materials seek to reduce the stress and the uncertainty that writers face when they encounter the blank page. But the attempt to produce certainty through standardization by-passes the opportunity for child growth. There is good reason to expect tension when a child first writes.</p>
<p>When writers write, they face themselves on the blank page. That clean white piece of paper is like a mirror. When I put words on the page, I construct an image of myself on that whiteness. I may not like my spelling, handwriting, choice of words, aesthetics, or general cleanliness of the page. Until I can begin to capture what I want to say, I have to be willing to accept imperfection and ambiguity. If I arrive at the blank page with a writing history filled with problems, I am already predisposed to run from what I see. I try to hide my paper, throw it away, or mumble to myself, &quot;This is stupid.&quot; But with every dangerous, demanding situation, there is an opportunity to learn. Teachers who follow and accompany children as they compose help them to deal with what they see on the page. The reason writing helps children with learning disabilities is that they do far more than learn to write: They learn to come to terms with a new image of themselves as thinkers-thinkers with a message to convey to the world.</p>
<h2>Teaching writing- two basic principles</h2>
<p class="shortbottompad">After 12 years of working with writing research and the teaching of writing, I have found two principles essential for effective teaching of writing:</p>
<ol>
  <li>The teacher teaches most by showing how he/she learns, and</li>
  <li>the teacher provides a highly structured classroom.</li>
</ol>
<p>The best demonstration of how teachers learn is through their gathering of information from the children. They place the children in the position of teaching them what they know, usually through conferences. &quot;Now you say that you have to be careful how deep you plant lettuce, Billy. Can you tell me more about that? And do you think the precise depth should be in your piece for the other children? Will they want to know that?&quot; Billy's teacher has shown him how she learns and how he should learn to listen to questions he soon will be able to ask himself.</p>
<p>Ms. Richards, Billy's teacher, has a basic lifestyle of learning from everyone. Whether seated next to someone on a plane, in the teachers' room, or talking informally with children, she wants to be taught; in a lifetime she has learned how important it is to help others to teach her. People leave Ms. Richards' presence surprises they knew so much about their subjects.</p>
<p>Ms. Richards' classroom is a highly structured, predictable classroom. Children who learn to exercise choice and responsibility can function only in a structured room. Furthermore, the up-and-down nature of the writing process itself demands a carefully defined room. Predictability means that writing occurs daily, at set times, with the teacher moving in the midst of the children, listening to their intentions, worries, and concerns. They know she will be nearby attending to their work. She rarely addresses the entire class during writing time. She works hard to establish a studio atmosphere. Predictability also means she won't solve problems for them. Rather, she asks how they might approach the problem. She listens, clarifies their intentions and their problems, and moves on.</p>
<p>Children learn to take responsibility not only for their topics, content of their drafts, and final copy, but also for carrying out classroom decisions. A structured classroom requires an organized teacher who has set the room up to run itself. The teacher has already made a list of the things to be done to help the room function. From September through June, he/she gradually passes on those duties to the children. Attendance, caring for room plants and animals, room cleanliness, lunch lines, desk supervision, and cleaning are but a few examples of these delegations. When room structure and routine do not function well, the teacher and students plan together for the best way to make it function more smoothly. Ms. Richards' room is based on extensive preparation in room design and knowledge of materials, the children, and the process by which they learn to take responsibility.</p>
<p>Teachers who function well in teaching the writing process are interested in what children have to teach them. Writing-process teaching is responsive, demanding teaching that helps children solve problems in the writing process and in the classroom.</p>
<h2>Carrying out a writing-process program</h2>
<p>I am often asked, &quot;What are the essentials to strong writing programs?&quot; Although the list could be extensive, I think that if teachers understand the following four components, their writing programs will serve the children well. These components are adequate provision of time, child choice of topic, responsive teaching, and the establishment of a classroom community, a community that has learned to help itself.</p>
<h2>Time</h2>
<p>Our data show that children need to write a minimum of 4 days a week to see any appreciable change in the quality of their writing. It takes that amount of writing to contribute to their personal development as learners. Unless children write at least 4 days a week, they won't like it. Once-a-week writing (the national average is about 1 day in 8) merely reminds them they can't write; they never write often enough to listen to their writing. Worse, the teacher simply has no access to the children. He/she has to scurry madly around the room trying to reach each child. With little access to the children, the teacher can't help them take responsibility, solve problems for them, or listen to their responses and questions. The very important connection between speaking and writing is lost.</p>
<p class="shortbottompad">Although teaching writing 4 to 5 times a week helps the teacher, it helps the children even more. When children write on a daily basis, we find they write when they aren't writing. Children get into their subjects, thinking about their texts and topics when they are riding on buses, lying in bed, watching television, reading books, or taking trips. When they write regularly, papers accumulate. There is visible evidence they know and are growing. They gain experience in choosing topics and very soon have more topics to write about than class time can accommodate. Children with learning problems need even more time. They need to team to listen to themselves with help front the teacher. In summary, regular writing helps:</p>
<ol>
  <li>Children choose topics,</li>
  <li>Children listen to their pieces and revise</li>
  <li>Children help each other,</li>
  <li>Teachers listen to child texts</li>
  <li>Skills develop in the context of child pieces</li>
  <li>Teachers to have greater access to children.</li>
</ol>
<h2>Topic choice</h2>
<p>The most important thing children can learn is what they know and how they know it. Topic choice, a subject the child is aware that he knows something about, is at the heart of success in writing. Billy struggled with handwriting and spelling and equated those problems with not knowing topics to write about. When his teacher helped him to discover his knowledge and interest in gardening, he began to write, first haltingly, then with greater flow. He was open to help with spelling and handwriting when he knew he had something to say. Skills are important; learning disabilities cannot be ignored, but neither can teachers or researchers forget that writing exists to communicate with self and others.</p>
<p>&quot;How can I get the child to write? Do you have any good motivators?&quot; are frequent questions asked of me in workshops. The word get embraces the problem. There are thousands of &quot;motivators&quot; on the market in the form of story starters, paragraph starters, computer software, animated figures, picture starters, and exciting &quot;sure-fire&quot; interest getters. We forget that children are very sophisticated consumers of motivators from Saturday morning television alone. Worse, motivators teach the child that the best stimulus comes from the outside. Writing actually demands dozens of motivators during the course of composing, but they are motivators that can only be supplied by the writer himself. All children have important experiences and interests they can learn to tap through writing. If children are to become independent learners, we have to help them know what they know; this process begins with helping children to choose their own topics.</p>
<p>Very young children, ages 5 through 7, have very little difficulty choosing topics, especially if they write every day. As children grow older and experience the early effects of audience, even under favorable learning conditions, they begin to doubt what they know. From that point on, all writers go through a kind of doubting game about the texts they produce. They learn to read better and are more aware of the discrepancy between their texts and their actual intentions. If, however, overly severe, doubting teachers are added to the internal doubts of the child, writing becomes still more difficult.</p>
<p>If children write every day and share their writing, we find they use each other as the chief stimulus for topic selection. If teachers write with their children, demonstrating the origin of their topics, and surround the children with literature, topic selection is even easier.</p>
<p>Topic selection is helped through daily journal writing where children take 10 minutes to record their thoughts. Teachers may also give 5- to 10-minute writing assignments, such as: &quot;Write about how you think our room could be improved&quot; just following a discussion about how the room could be improved with the entire class) or &quot;That upsets you? Well, blast away on paper with the first thoughts that come to mind. But write it for you; if you feel like showing it to me, okay.&quot; The teacher finds many occasions where it is useful to record thoughts and opinions on paper. Each of these approaches demonstrates what writing is for, as well as helping the children to have access to what they know and think.</p>
<h2>Response</h2>
<p>People write to share, whether with themselves or others. Writers need audiences to respond to their messages. The response confirms for the writer that the text fits his/her intentions. First, the teacher provides an active audience for the writer by confirming what he/she understands in the text and then by asking a few clarifying questions. Second, the teacher helps the entire class to learn the same procedure during group share time. Each writing period ends with two or three children sharing their pieces with the group while the group follows the discipline of first pointing to what is in the text, then asking questions to learn more about the author's subject. All of these responses, whether by the teacher or the other children, are geared to help writers learn to listen to their own texts.</p>
<p class="shortbottompad">While the children are writing, Billy's teacher moves around the room, responding to their work in progress. Here is an interchange Ms. Richards had with Billy about his piece &quot;My Garden.&quot; (The child's text is presented, followed by the conference with the teacher.)</p>
<blockquote>
  <h3>My Grdan</h3>
  <p>I help my Dad with the grdan ferstyou have to dig it up an than you rake an get the racks out of it. Than you make ros an you haveto be cerfull to make it deep enuff so the letis will come up.</p>
</blockquote>
<p class="shortbottompad">Ms. Richards first receives the piece by saying what she understands about what Billy has written. She may also have him read the writing aloud to her:</p>
<blockquote>
  <p>Ms. Richards: You've been working hard, Billy. I see that you work with your dad on your garden. You know just what you do; you dig it up, rake it to get the rocks out, and then you have to be careful how deep you plant things. Did I get that right?</p>
  <p>Billy: Yup.</p>
  <p>Ms. Richards: Well, I was wondering, Billy. You say that the lettuce has to be planted deep enough so the lettuce will come up. Could you tell me more about that? I haven't planted a garden for a long time.</p>
  <p>Billy: Well, If you plant it too deep, it won't come up. Lettuce is just near the top.</p>
  <p>Ms. Richards: Oh, I see and did you plant some other things in your garden?</p>
  <p>Billy: Yup, carrots, beans, turnips (I hate 'em), spinach (that, too) beets, and tomatoes; I like tomatoes.</p>
  <p>Ms. Richards: That's quite a garden, Billy. And what will you be writing here next?</p>
  <p>Billy: You have to water it once you plant it.</p>
  <p>Ms. Richards: Then you already know what you'll be doing, don't you.</p>
</blockquote>
<p>There are many problems with Billy's text: misspelled words, run on sentences, missing capitalizations, and incomplete information. But Billy has just started writing his piece. Therefore, Ms. Richards works on word flow, helping Billy to know that he knows something about his subject and that he has a clear understanding of what he will do next. Later, when his piece is finished, she will choose one skill to teach within the context of his topic. Above all, she works hard to help Billy teach her about his subject, to keep control of the topic in his hands, no matter how uncertain Billy might feel about his subject.</p>
<p>Notice that Ms. Richards has spent no more than a minute and a half in response. She then moves to other children while responding in the same manner, receiving a text and asking questions. As she moves to different children in other parts of the room (she does not move in rotation or down rows; the movement appears to be random), the other children can hear that the teacher expects them to help her with what they know. Lengthy responses tend to take the writing away from the child. For example, if Ms. Richards were to say, &quot;I had a garden once, Billy. I planted all kinds of things too: I planted cabbages, those same turnips, yellow beans, pole beans, and corn. Yes, It's hard work,&quot; she'd be identifying with Billy's garden and the hard work that goes into it, but she's now the informant. Such sharing should come only when his piece is completed and his authorship of this piece established.</p>
<p>Ms. Richards' statement is specific. When she receives Billy's text, she uses the actual words he has composed on the page. All writers need to know their words (the actual words on the page) affect other people. Notice that very little praise is given to Billy in this type of response. Instead, the listener, Ms. Richards, points with interest to the words; they are strong enough for her to understand and to remember them. The use of specifics, rather than the exclusive use of praise, is a fundamental issue in helping Billy to maintain control of his piece, as well as to take more responsibility for his text.</p>
<p><a href="article/6204#anchor916482">Top of Page</a></p>
<h2>Establish a community of learners</h2>
<p>Writing is a social act. If social actions are to work, then the establishment of a community is essential. A highly predictable classroom is required if children are to learn to take responsibility and become a community of learners who help each other. Writing is an unpredictable act requiring predictable classrooms both in structure and response.</p>
<p class="shortbottompad">Children with learning disabilities often have histories of emotional problems. Many have become isolated and feel very little sense of community. They themselves may produce unpredictable classrooms. Their histories in taking responsibility are equally strewn with failure. Notions of choice and responsibility are threatening and require careful work on a broad front. The following ingredients help to build a structured, predictable community of more independent writers.</p>
<ol>
  <li>Write daily, at the same time if possible, for a minimum of 30 minutes.</li>
  <li>Work to establish each child's topical turf, an area of expertise for each writer.</li>
  <li>Collect writing in folders so that writers can see the accumulation of what they know. Papers do not go home; rather, the collected work is present in class for student, teacher, parent, and administrator to examine. Some writing is published in hardcover or some more durable form.</li>
  <li>Provide a predictable pattern of teacher participation by sharing your own writing, moving in the midst of students during writing time, and responding in predictable structure to your students' writing.</li>
  <li>End each writing time with children responding to each other's writing in a predictable format: receiving, questioning.</li>
  <li>Set up classroom routines in which you examine the entire day to see which responsibilities can be delegated to the children. Solve room problems in discussion. The group learns to negotiate, whether in working with a draft or solving a classroom problem.</li>
  <li>Continually point to the responsibilities assumed by the group, as well as the specifics of what they know.</li>
</ol>
<p>The writing classroom is a structured, predictable room in which children learn to make decisions. The external structure is geared to produce a confident, internal thinking framework within which children learn what they know and develop their own Initiative.</p>
<h2>Continuing education of professionals</h2>
<p>Most teachers have been drawn into process work because they have seen significant personal growth by their students with learning problems. Students who lacked confidence and initiative and were disenfranchised from literacy learn to write, share their writing with others, and take charge of their own learning. Although some teachers may wish to start work on the writing process based on this article, I suggest additional reading and work with their own writing.</p>
<p>The single most important help to teachers who work with young writers is work with the teacher's own writing. Both the National Writing Project and our work here at the University of New Hampshire stress work with the teacher's own writing. Thus teachers become acquainted with writing from the inside by actually doing it themselves. It would be unheard of for a piano teacher, a ceramicist, or an artist working with water colors to teach someone their craft without practicing it themselves. Most of us have had little instruction in learning the craft of writing. We've written term papers, letter, and proposals, but we haven't worked with someone who has helped us to know what we know, then showed us how that knowledge is increased through the writing process.</p>
<h2>Final reflection</h2>
<p>Before children go to school, their urge to express is relentless. They learn to speak and to carry messages from one person to another. They burst into their homes to tell what just happened outside. They compose in blocks, play games, mark on sidewalks, and play with pencils or crayons. For most children, early audiences are receptive: adults struggle to make sense of the child's early attempts to communicate.</p>
<p>When children enter school, their urge to express is still present. A few enter already scarred from attempts to communicate with others. But the urge to be, to make a mark on the universe, has not left them. As children grow older and spend more time in school, many become still more disenchanted with writing. They can't keep up with the rest of the class and equate their struggles with handwriting, spelling, and early conventions as evidence that their ideas are unacceptable and that they are less intelligent than others. Even for these children, the urge to express, to make worthwhile contributions, to express a meaning that affects others, does not go away.</p>
<p>The most critical factor for children with learning disabilities is the meaning-making question. Teachers need to first believe they know important information, then work overtime to confirm for the child the importance of that information. The children see their teachers write; they see and hear them struggle for meaning on an easel or overhead projector as they compose before them. The children become apprentices to the use of words.</p>
<p>When children write, they make mistakes on the road to communicating their messages. The teacher's first response is to the meaning. Before a piece is completed, the teacher chooses one skill that will enhance the meaning of the piece still further. From the beginning, the teacher works to build a strong history for writers through collections of all their work, some publishing, and the writers' effective sharing with other members of the class.</p>
<p>Most teaching of writing is pointed toward the eradication of error, the mastery of minute, meaningless components that make little sense to the child. Small wonder. Most language arts texts, workbooks, computer software, and reams of behavioral objectives are directed toward the &quot;easy&quot; control of components that will show more specific growth. Although some growth may be evident on components, rarely does it result in the child's use of writing as a tool for learning and enjoyment. Make no mistake, component skills are important; if children do not learn to spell or use a pencil to get words on paper, they won't use writing for learning any more than the other children drilled on component skills. The writing-process approach simply stresses meaning first, and then skills in the context of meaning. Learning how to respond to meaning and to understand what teachers need to see in texts takes much preparation.</p>
<p>The writing process places high demands on the teacher. The room is carefully designed for developing student independence: Decisions are discussed, responsibilities assigned and assumed. Routines are carefully established with writing becoming a very important part of the room's predictability. Initially, response to the child's writing is predictable with receiving of the child's text, followed by questions of clarification, and the child's next step in the writing process.</p>
<p>Teachers who use the writing process to greatest advantage spend time working with their own writing. They read and become involved in many of the National Institutes that are helping teachers use writing as a tool for their own learning. Soon they find their students' learning careers change as well.</p>
<h2>About the author</h2> 
<p>Donald Graves is Professor of Education at the University of New Hampshire and Director of the Writing Process Laboratory there. He received his EdD degree from the State University of New York at Buffalo in 1973. He has conducted studies of children's writing and reading since 1972, and In 1982 received the annual David H. Russet Award for Excellence in Research. He has also written or edited four books on the teaching of writing and reading. Address. Dr. Donald Graves, Professor of Education, University of New Hampshire, Durham NH 03824.</p>
<p><a href="article/6204#anchor916482">Top of Page</a></p>
<div class="contentbox">
			<p class="pagenote">Donald H. Graves University of New Hampshire Learning Disabilities Focus, 1985</p>
	</div>