<h2>Edreform</h2>
  <ul class="follow">
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.viewfromtheedge.net/" title="News and Notes from Oklahoma Educator Rob Miller">Rob Miller</a> <span class="p-note"> News and Notes from Oklahoma Educator Rob Miller</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://edexcellence.net/blog-types/flypaper" title="The flypaper is the Fordham Institute blog"> Mike Petrelli</a> <span class="p-note"> The flypaper is the Fordham Institute blog</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.aei.org/profile/andrew-smarick/" title="structure and function of urban districts, but he also returns often to the questions of traditional conservative thought">Andy Smarick</a> <span class="p-note"> structure and function of urban districts, but he also returns often to the questions of traditional conservative thought</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://edexcellence.net/about-us/fordham-staff/robert-pondiscio" title="  Robert Pondiscio is senior fellow and vice president for external affairs at the Thomas B. Fordham Institute"><img class="u-photo" src="http://edex.s3-us-west-2.amazonaws.com/bio/staff_images/Robert%20Pondiscio%20-%20edit.jpg"  alt="" /> Robert Pondiscio</a> <span class="p-note">   Robert Pondiscio is senior fellow and vice president for external affairs at the Thomas B. Fordham Institute</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://blogs.edweek.org/edweek/rick_hess_straight_up/" title="A conservative&#8217;s conservative">Rick Hess</a> <span class="p-note"> A conservative&#8217;s conservative</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://jaypgreene.com/" title="Strong on parental choice.">Jay P. Greene</a> <span class="p-note"> Strong on parental choice.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.cato.org/people/1680/blog" title="Cato Fellow. Hates federal role in education">Neal McCluskey</a> <span class="p-note"> Cato Fellow. Hates federal role in education</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://medium.com/@DmitriMehlhorn" title="Democratice activist and edreformer"><img class="u-photo" src="https://miro.medium.com/fit/c/240/240/0*DX9XoORkcYx9WTFg.jpeg"  alt="" /> Dmitiri Melhorn</a> <span class="p-note"> Democratice activist and edreformer</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://accountabaloney.com/" title="Accountabloney.com-Florida ">Sue Woltanski, Suzette Lopez</a> <span class="p-note"> Accountabloney.com-Florida </span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.alfiekohn.org/" title="criticisms of competition and rewards">Alfie Kohn</a> <span class="p-note"> criticisms of competition and rewards</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://andreagabor.com/" title="Bottom up model of edreform">Andrea Garbor</a> <span class="p-note"> Bottom up model of edreform</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.washingtonpost.com/news/answer-sheet/?noredirect=on&#038;utm_term=.ac70906ae5e6" title="Anti Common Core Crusdader, mucracker">Valarie Strauss</a> <span class="p-note"> Anti Common Core Crusdader, mucracker</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://adambessie.com/" title="Illustrator and school activisit">Adam Bessie</a> <span class="p-note"> Illustrator and school activisit</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://badassteachers.blogspot.com/" title="Edreform activist group on the side of teachers"><img class="u-photo" src="http://1.bp.blogspot.com/--UEH9MATA78/UyTvDjx4XOI/AAAAAAAAAw8/_VuRXTcMB7k/s1600/batapple.png"  alt="Bad Ass Teacher Association Edreform activist group on the side of teachers"  title="Edreform activist group on the side of teachers" /> Bad Ass Teacher Association</a> <span class="p-note"> Edreform activist group on the side of teachers</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://bigeducationape.blogspot.com/" title="One of the best aggregators of edublogging out there.">Big Education Ape</a> <span class="p-note"> One of the best aggregators of edublogging out there.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://Busted%20Pencils" title="unabashedly progressive and activist">https://bustedpencils.com/</a> <span class="p-note"> unabashedly progressive and activist</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://bluecerealeducation.com/" title="Northern Indiana public school teacher, edu-consultant, and workshop guru.">Blue Cereal Education</a> <span class="p-note"> Northern Indiana public school teacher, edu-consultant, and workshop guru.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.bobbraunsledger.com/" title="NJ education activitst">Bob Braun</a> <span class="p-note"> NJ education activitst</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://www.brightlightsmallcity.com/" title="Sarah Lahm  freelance journalist, specializing in tracking education reform and its impact on parents, teachers, students, and staff of the Minneapolis Public Schools."><img class="u-photo" src="https://i0.wp.com/www.brightlightsmallcity.com/wp-content/uploads/2015/02/DSCN2214.jpg"  alt="Sarah Lahm Sarah Lahm  freelance journalist, specializing in tracking education reform and its impact on parents, teachers, students, and staff of the Minneapolis Public Schools."  title="Sarah Lahm  freelance journalist, specializing in tracking education reform and its impact on parents, teachers, students, and staff of the Minneapolis Public Schools." /> Sarah Lahm</a> <span class="p-note"> Sarah Lahm  freelance journalist, specializing in tracking education reform and its impact on parents, teachers, students, and staff of the Minneapolis Public Schools.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://www.chicagonow.com/chicago-public-fools" title="Critical look at Chicago Education Poilicy">Julie Vassilatos</a> <span class="p-note"> Critical look at Chicago Education Poilicy</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://cloakinginequity.com/" title=" is an award-winning teacher, researcher, and blogger.">Julian Vasquez Heilig</a> <span class="p-note">  is an award-winning teacher, researcher, and blogger.</span></li>

  </ul>