<h2 class="p-category" id="edtech" value="edtech">edtech</h2>
  <ul class="follow-of follow">
    <li class="h-card p-follow-of"><a class="p-name u-url" href="http://blog.jasongreen.net/" rel="colleague">Jason Green</a><span class="p-note">þoht-hord an exercise in personal knowledge management
</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="http://kellyhilton.org" rel="colleague muse">Kelly Hilton</a> <span class="p-note">  bike riding, kayaking, camping, yoga, family, good food, creative tech projects
</span></li>
<li class="h-card p-follow-of"><a class="p-name u-url" href="http://gamedevprofessor.com/" rel="colleague muse">Ken Thompson</a> <span class="p-note">game designer and educator.
</span></li>
<li class="h-card p-follow-of"><a class="p-name u-url" href="http://www.drrobinkay.org/" rel="colleague muse">Robin Kay</a> <span class="p-note">Professor University of Ontario Institute of Technology</span></li>
    <li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.linkedin.com/in/susanmbearden/" rel="colleague muse">Susan Bearden</a><span class="p-note">Chief Innovation Officer at Consortium for School Networking (CoSN)</span><span class</li>
    <li class="h-card p-follow-of"><a class="p-name u-url"  href="https://anderson-edtech.blogspot.com/" title="Level 1 &amp; 2 Google Certified Educator, Pear Deck Certified Coach, Vice President, CUE-NV," rel="colleague">Kyle Anderson</a><span class="p-note">Level 1 &amp; 2 Google Certified Educator, Pear Deck Certified Coach, Vice President, CUE-NV,</span></li>
<li class="h-card p-follow-of"><a class="p-name u-url"  href="https://www.linkedin.com/in/rdavis9/" title="Founding Principal at Pathways in Technology Early College High School" rel="colleague muse"> Rashid Davis</a><span class="p-note">Founding Principal at Pathways in Technology Early College High School</span></li>
<li class="h-card p-follow-of"><a class="p-name u-url"  href="https://techagogy.weebly.com/" title="Technology Integration Specialist, English Teacher, Media Arts instructor, Apple Distinguished Educator, Lead PBS Digital Innovator" rel="colleague muse"><img class="u-photo" src="https://techagogy.weebly.com/uploads/8/6/4/5/8645487/published/dan-koch-edu-app-001.png?1509120088"  alt="Dan Koch Technology Integration Specialist, English Teacher, Media Arts instructor, Apple Distinguished Educator, Lead PBS Digital Innovator"  title="Technology Integration Specialist, English Teacher, Media Arts instructor, Apple Distinguished Educator, Lead PBS Digital Innovator" /> Dan Koch</a><span class="p-note">Technology Integration Specialist, English Teacher, Media Arts instructor, Apple Distinguished Educator, Lead PBS Digital Innovatory</span></li>
<li class="h-card p-follow-of"><a class="p-name u-url"  href="http://www.aimeebartis.com/" title="Momma. Learner. Writer. Servant. Thinker of Big Thoughts. Reader. Learning &amp; Innovation Specialist " rel="colleague muse">Amy Bartis</a> <span class="p-note"> Momma. Learner. Writer. Servant. Thinker of Big Thoughts. Reader. Learning &amp; Innovation Specialist </span></li>
<li class="h-card p-follow-of"><a class="p-name u-url" href="https://rafranzdavis.com/" title="Rafranz Davis has dedicated her career to empowering students and teachers to share their voices throughout their communities and the world">Rafranz Davis</a> <span class="p-note">Rafranz Davis has dedicated her career to empowering students and teachers to share their voices throughout their communities and the world</span></li>
<li class="h-card p-follow-of"><a class="p-name u-url" href="http://www.stevehargadon.com" title="virtual, and peer-to-peer education conferences."><img class="u-photo" src="https://2.bp.blogspot.com/-Vkktz2QwBvU/WeIxiJ9wPmI/AAAAAAAKCaE/Hs2bIWnSwSghUCiabGYDkBKyj6_ShawYwCLcBGAs/s200/steve2017iste.jpg"  alt="Steve Hargadon virtual, and peer-to-peer education conferences."  title="virtual, and peer-to-peer education conferences." /> Steve Hargadon</a> <span class="p-note"> virtual, and peer-to-peer education conferences.</span></li>
<li class="h-card p-follow-of"><a class="p-name u-url" href="http://dangerouslyirrelevant.org/" title="edtech cnad school leadership">Scott McLeod</a> <span class="p-note"> edtech cnad school leadership</span></li>
<li class="h-card p-follow-of"><a class="p-name u-url" href="https://mashe.hawksey.info/" title="opened, edtech, google guru">Marin Hawksey</a> <span class="p-note"> opened, edtech, google guru</span></li>
<li class="h-card p-follow-of"><a class="p-name u-url" href="https://rickscafe.wordpress.com/" title="professor of educational technology and design at the University of Saskatchewan">Richard Schwier</a> <span class="p-note"> professor of educational technology and design at the University of Saskatchewan</span></li>
<li class="h-card p-follow-of"><a class="p-name u-url"  href="https://www.emergingedtech.com/" title="CIO at The College of Westchester in White Plains, NY"><img class="u-photo" src="https://www.emergingedtech.com/wp/wp-content/uploads/2017/03/New-Header-Hello-2017-1024x364.png"  alt="Kelly Wash CIO at The College of Westchester in White Plains, NY"  title="CIO at The College of Westchester in White Plains, NY" /> Kelly Wash</a> <span class="p-note"> CIO at The College of Westchester in White Plains, NY</span></li>
<li class="h-card p-follow-of"><a class="p-name u-url" href="http://vanmeterlibraryvoice.blogspot.com/" title="Shannon McClintock Miller is the K-12 district teacher librarian at Van Meter Community Schoo">Van Meter Library</a> <span class="p-note"> Shannon McClintock Miller is the K-12 district teacher librarian at Van Meter Community Schoo</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://theinnovativeeducator.blogspot.com/" title=" found school boring and irrelevant. That ticked her off"><img class="u-photo" src="https://lh3.googleusercontent.com/GRsR6Pa1QRCj-uGuRHgLSdMJGdWYcSLtiH-MuYwKOgBNrR7mUb_ShlUj-iRiUHnKoo5O82VQe-sKSeyZVlnpYVMKRwO9BA75iB_0FJTTdEeJN7ZIPq9CwZfJQg"  alt="Lisa Nielsen  found school boring and irrelevant. That ticked her off"  title=" found school boring and irrelevant. That ticked her off" /> Lisa Nielsen</a> <span class="p-note">  found school boring and irrelevant. That ticked her off</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://www.cgreenhow.org/" title="learning in social media contexts and the design of networked spaces">Christine Greenhow</a> <span class="p-note"> learning in social media contexts and the design of networked spaces</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://miriamposner.com/blog/" title="mapping to network analysis"><img class="u-photo" src="http://www.miriamposner.com/images/Miriam3.jpg"  alt="Miriam Posner mapping to network analysis"  title="mapping to network analysis" /> Miriam Posner</a> <span class="p-note"> mapping to network analysis</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.educatoralexander.com/honestly-desiree-blog" title="award winning super star edtech geek and teacher">Desiree Alexander</a> <span class="p-note"> award winning super star edtech geek and teacher</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.aliciajohal.com/" title="SOME   PEOPLE   ONLY DREAM  OF MEETING THEIR  favorite SCIENTISTS  I TEACH MINE">Alicia Johal</a> <span class="p-note"> SOME   PEOPLE   ONLY DREAM  OF MEETING THEIR  favorite SCIENTISTS  I TEACH MINE</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://www.fluttertech.org/" title="2016 Chicago Public School ‘Ones to Watch’ winner for technology innovation, is a premiere leader in the Ed Tech field">Taneesha A. Thomas</a> <span class="p-note"> 2016 Chicago Public School ‘Ones to Watch’ winner for technology innovation, is a premiere leader in the Ed Tech field</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://gowhereyougrow.wordpress.com/" title="focus on educational technology and teaching. But I tend to frequently change the object of my fascination"><img class="u-photo" src="https://secure.gravatar.com/avatar/fce5ae84b7ae97d1f2bd48d0e5f45024?s=160&amp;d=monsterid&amp;r=pg"  alt=""  title="focus on educational technology and teaching. But I tend to frequently change the object of my fascination" /> Shawn McCusker</a> <span class="p-note"> focus on educational technology and teaching. But I tend to frequently change the object of my fascination</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://worlds-of-learning.com/" title=" professional learning experiences that will empower and equip educators with necessary STEM-education related skills"><img class="u-photo" src="https://worlds-of-learning.com/wp-content/uploads/2018/08/IMG_7060-e1535505277802-768x1022.jpg"  alt=""  title=" professional learning experiences that will empower and equip educators with necessary STEM-education related skills" /> Laura Fleming</a> <span class="p-note">  professional learning experiences that will empower and equip educators with necessary STEM-education related skills</span></li>
    <li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.sowevebeenthinking.com/" title="tell the stories that needs to be heard to grow the conversation about education, technology &amp; innovation in schools. ">Greg Kulowiec</a><span class="p-note">tell the stories that needs to be heard to grow the conversation about education, technology &amp; innovation in schools. </span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://brholland.com/" title="Write for a number of publications including EdTech Researcher at EducationWeek and Edutopia, ">Beth Holland</a> <span class="p-note"> Write for a number of publications including EdTech Researcher at EducationWeek and Edutopia, </span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://linktr.ee/thetechrabbi" title="Designer, Educator, Creativity Instigator. M.S.Ed, Author, Speaker"><img class="u-photo" src="https://d15mvavv27jnvy.cloudfront.net/wgWVL/5bc0b3c05522a1e6fff33bbe99904c39.jpg%3F_nc_eui2%3DAeHqMKN9FEHPnMZ5qD8i7MkaSrtuAUop2UbLW0FithLODBqTGTkZ7-JiKPTLJ_IugdNvD8mxsD5YErrPgle0PoW-"  alt="Rabbi Michael Cohen Designer, Educator, Creativity Instigator. M.S.Ed, Author, Speaker"  title="Designer, Educator, Creativity Instigator. M.S.Ed, Author, Speaker" /> Rabbi Michael Cohen</a> <span class="p-note"> Designer, Educator, Creativity Instigator. M.S.Ed, Author, Speaker</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://www.danryder207.com/" title="Co-Author of Intention: Critical Creativity http://bit.ly/in10tionthebook"><img class="u-photo" src="https://danryder207.files.wordpress.com/2014/07/screen-shot-2014-04-02-at-7-58-20-pm.png?w=600&amp;h=498"  alt=""  title="Co-Author of Intention: Critical Creativity http://bit.ly/in10tionthebook" /> Dan Ryder</a> <span class="p-note"> Co-Author of Intention: Critical Creativity http://bit.ly/in10tionthebook</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.aiaddysonzhang.com/" title="speak the language of social media, of emojis, of gifs, and of &#8220;lol&#8221; or &#8220;rofl.&#8221;">Ai Addyson-Zhang</a> <span class="p-note"> speak the language of social media, of emojis, of gifs, and of &#8220;lol&#8221; or &#8220;rofl.&#8221;</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://teresa-nextsteps.blogspot.com/" title="Tout est possible &#8211; Talleyrand (mais tout n&#8217;est pas souhaitable &#8211; Teresa)">Teresa Mackinnon</a> <span class="p-note"> Tout est possible &#8211; Talleyrand (mais tout n&#8217;est pas souhaitable &#8211; Teresa)</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.claireamos.com/" title=" passionate about her family, education, fashion and tattoos, living by the mantra &#8211; “you can never be overdressed or overeducated">Claire Amos</a> <span class="p-note">  passionate about her family, education, fashion and tattoos, living by the mantra &#8211; “you can never be overdressed or overeducated</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://catlintucker.com/" title="Catlin Tucker is a Google Certified Innovator, bestselling author, international trainer, and frequent Edtech speaker"><img class="u-photo" src="https://catlintucker.com/wp-content/uploads/2010/08/Catlin-Tucker-High-Res-Photo.jpg"  alt=""  title="Catlin Tucker is a Google Certified Innovator, bestselling author, international trainer, and frequent Edtech speaker" /> Caitlin Tucker</a> <span class="p-note"> Catlin Tucker is a Google Certified Innovator, bestselling author, international trainer, and frequent Edtech speaker</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://ryan2point0.wordpress.com" title="earning Innovation Manager in the Australian financial services sector."><img class="u-photo" src="https://ryan2point0.files.wordpress.com/2013/05/ryan_02f_148.png?w=148&amp;h=148&amp;zoom=2"  alt="" /> Ryan Tracey</a> <span class="p-note"> earning Innovation Manager in the Australian financial services sector.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.drdouggreen.com/" title="Bite-Sized daily Self-Development. It focuses on book summaries that present the main concepts of important books in about 15 paragraphs"><img class="u-photo" src="https://www.drdouggreen.com/wp-content/uploads/DSC06799-300x225.jpg"  alt=""  title="Bite-Sized daily Self-Development. It focuses on book summaries that present the main concepts of important books in about 15 paragraphs" /> Doug Green</a> <span class="p-note"> Bite-Sized daily Self-Development. It focuses on book summaries that present the main concepts of important books in about 15 paragraphs</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://etale.org/main/" title="life, education, learning, innovation, transcendentals, curiosity and wonder, meaning and purpose, entrepreneurship, and leadership in a connected world">Bernard Bull</a> <span class="p-note"> life, education, learning, innovation, transcendentals, curiosity and wonder, meaning and purpose, entrepreneurship, and leadership in a connected world</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.thedaringlibrarian.com/" title="meme archivist, creator of content, a citizen of advocacy, and a resident of social media"><img class="u-photo" src="https://4.bp.blogspot.com/-DorrRpPrXYU/Vx19lMOAlKI/AAAAAAAABkY/VfsX841bGm8-LdlikAjk2Z4dlmCmqHzsQCK4B/s113-pf/GAJ_Glasses_CircBLK.jpg"  alt="" /> Gwyneth A. Jones</a> <span class="p-note"> meme archivist, creator of content, a citizen of advocacy, and a resident of social media</span></li>

  </ul>