<h2>IndieWeb</h2>
  <ul class="follow">
    <li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.bridgestew.com/" title="Bridget co-founded an annual Web Design and Development conference in Cleveland called Rustbelt Refresh.">Bridget Stewart</a> <span class="p-note">Bridget co-founded an annual Web Design and Development conference in Cleveland called Rustbelt Refresh.</span></li>
    <li class="h-card p-follow-of"><a class="p-name  u-url" href="https://adamdawkins.uk/" title="Adam is a web developer. I co-founded and work at Dragon Drop. Based in High Wycombe, United Kingdom.">Adam Dawkins</a> <span class="p-note"> Adam is a web developer. I co-founded and work at Dragon Drop. Based in High Wycombe, United Kingdom.</span></li>
     <li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.svenknebel.de" title="Sven is an IndieWeb organizer, developer, and created a still nameless system for his website">Sven Knebel</a> <span class="p-note"> Sven is an IndieWeb organizer, developer, and created a still nameless system for his website.</span></li>
    <li class="h-card p-follow-of"><a class="p-name  u-url" href="https://petergasston.co.uk/" title="SPeter investigaets emerging technologies and user behaviour">Peter Gaston</a> <span class="p-note"> Peter investigaets emerging technologies and user behaviour</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://werd.io" rel="colleague" title="Ben is an IndieWeb developer and blogger founder of Known and Elgg">Ben Werdmuller</a> <span class="p-note"> Ben is an IndieWeb developer and blogger founder of Known and Elgg</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://adactio.com/" title="My name is Jeremy. I make websites. "><img class="u-photo" src="https://adactio.com/images/photo-300.jpg"  alt=""  title="My name is Jeremy. I make websites. " /> Jeremy Kieth</a> <span class="p-note"> My name is Jeremy. I make websites. </span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://tantek.com/" title="Inventor, writer, teacher, runner, coder">Tantek Çelik</a> <span class="p-note"> Inventor, writer, teacher, runner, coder</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://aaronparecki.com/" title="co-founder of IndieWebCamp."><img class="u-photo" src="https://aaronparecki.com/images/profile.jpg"  alt=""  title="co-founder of IndieWebCamp." /> Aaron Parecki</a> <span class="p-note"> co-founder of IndieWebCamp.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://vanderven.se/martijn/" title="Has world&#8217;s longest h-card">Martijn van der Ven</a> <span class="p-note"> Has world&#8217;s longest h-card</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://david.shanske.com/" title="Doer of all thigns WordPress"><img class="u-photo" src="https://david.shanske.com/wp-content/uploads/avatar-privacy/cache/gravatar/2/c/2cb1f8afd9c8d3b646b4071c5ed887c970d81d625eeed87e447706940e2c403d-250.png"  alt="" /> David Shanske</a> <span class="p-note"> Doer of all thigns WordPress</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://martymcgui.re/" title="freelance web developer in Baltimore, MD. I can also be found tinkering with electronics, 3D printing, and performing improv comedy.">Marty McGuire</a> <span class="p-note"> freelance web developer in Baltimore, MD. I can also be found tinkering with electronics, 3D printing, and performing improv comedy.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://sonniesedge.co.uk/posts" title="horse riding, photography-taking, bike riding, beer drinking, feminist leftie; a strawberry-blonde gay woman, with her head always buried in a book."><img class="u-photo" src="https://d33wubrfki0l68.cloudfront.net/a89fa64fa3851263abd4f1fe16a23aebe0926a58/b598d/images/pages/photo.jpg"  alt="" /> sonniesedge</a> <span class="p-note"> horse riding, photography-taking, bike riding, beer drinking, feminist leftie; a strawberry-blonde gay woman, with her head always buried in a book.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://unicyclic.com/mal/blog" title="nice guy and developer from Brisbane">Malcom Blaney</a> <span class="p-note"> nice guy and developer from Brisbane</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.jeremycherfas.net/" title=" I see myself as a translator. I speak Science, and I speak English, and I work hard to make the two understand one another. ">Jeremey Cherfas</a> <span class="p-note">  I see myself as a translator. I speak Science, and I speak English, and I work hard to make the two understand one another. </span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://jeena.net/" title="I live in Sweden, brew beer, dry meat, play metal and develop games and other software."><img class="u-photo" src="https://jeena.net/avatar_home.jpg"  alt=""  title="I live in Sweden, brew beer, dry meat, play metal and develop games and other software." /> Jeena Paradise</a> <span class="p-note"> I live in Sweden, brew beer, dry meat, play metal and develop games and other software.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.marcus-povey.co.uk/" title="Superstar Known Wrangler">Marcus Povey</a> <span class="p-note"> Superstar Known Wrangler</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://www.kevinmarks.com/" title="Main blog site">Kevin Marks</a> <span class="p-note"> Main blog site</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://petermolnar.net/" title="went through a cycle of Microsoft FrontPage, a self-composed, PHP CMS, WordPress, and now I&#8217;m back on static(ish) site generation since 2016: "><img class="u-photo" src="https://petermolnar.net/favicon.png"  alt=""  title="went through a cycle of Microsoft FrontPage, a self-composed, PHP CMS, WordPress, and now I&#8217;m back on static(ish) site generation since 2016: " /> Peter Molnar</a> <span class="p-note"> went through a cycle of Microsoft FrontPage, a self-composed, PHP CMS, WordPress, and now I&#8217;m back on static(ish) site generation since 2016: </span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://gregorlove.com/" title="music · faith · computer geekery · friends · liberty">gRegor Love</a> <span class="p-note"> music · faith · computer geekery · friends · liberty</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://miklb.com/" title="Chef, web mechanic, general mayhem maker. "><img class="u-photo" src="https://secure.gravatar.com/avatar/c39a1d6df73525945cfe50e99dada730?s=98&amp;d=https://miklb.com/content/plugins/semantic-linkbacks/img/mm.jpg&amp;r=r"  alt="" /> Michael Bishop</a> <span class="p-note"> Chef, web mechanic, general mayhem maker. </span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://ascraeus.org/" title="Father, Tinkerer, Indieweb Enthusiast. Writer of influential words. Probably a commahnist.">Daniel Gold</a> <span class="p-note"> Father, Tinkerer, Indieweb Enthusiast. Writer of influential words. Probably a commahnist.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://eddiehinkle.com/" title="Eddie Hinkle is a husband to Ashley, father to Luke and UI Engineer that lives in Frederick, MD.">Eddie Hinkle</a> <span class="p-note"> Eddie Hinkle is a husband to Ashley, father to Luke and UI Engineer that lives in Frederick, MD.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://realize.be/" title="On art, music, mobile, drupal, stars, flying things and planets">Kristof De Jaeger</a> <span class="p-note"> On art, music, mobile, drupal, stars, flying things and planets</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://veganstraightedge.com/" title="Formerly, The Farmhouse in Hollywood, California and #LittleMisadventureTime, and defeated cancer. ">Shane Becker</a> <span class="p-note"> Formerly, The Farmhouse in Hollywood, California and #LittleMisadventureTime, and defeated cancer. </span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://peterstuifzand.nl/"><img class="u-photo" src="https://peterstuifzand.nl/img/profile.jpg"  alt=""  /> Peter Stuifzand</a><span></span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://jackjamieson.net/" title=" PhD candidate at the University of Toronto’s Faculty of Information. My research investigates how underlying infrastructures and platforms affect online communication."><img class="u-photo" src="https://secure.gravatar.com/avatar/c850ec9240a04bd1ebf02540e4f57b73?s=250&amp;d=default&amp;r=g"  alt="Jack Jamieson  PhD candidate at the University of Toronto’s Faculty of Information. My research investigates how underlying infrastructures and platforms affect online communication."  title=" PhD candidate at the University of Toronto’s Faculty of Information. My research investigates how underlying infrastructures and platforms affect online communication." /> Jack Jamieson</a> <span class="p-note">  PhD candidate at the University of Toronto’s Faculty of Information. My research investigates how underlying infrastructures and platforms affect online communication.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://boren.blog/" title="retired software developer, former lead developer of WordPress, and co-conspirator emeritus at Automattic">Ryan Boren</a> <span class="p-note"> retired software developer, former lead developer of WordPress, and co-conspirator emeritus at Automattic</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://islandinthenet.com/" title="inchoate ramblings on technology, photography, beer, and geekery"><img class="u-photo" src="https://secure.gravatar.com/avatar/7fa94585b903e6e183d6164b16b1b573?s=252&amp;d=default&amp;r=pg"  alt="" /> Khürt Williams</a> <span class="p-note"> inchoate ramblings on technology, photography, beer, and geekery</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://ramblinggit.com/" title="Thoughts from my stylish, mysterious, perilous life.">https://ramblinggit.com/</a> <span class="p-note"> Thoughts from my stylish, mysterious, perilous life.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://esham.io/" title="trying out all the stuff and just as confused as the rest of us."><img class="u-photo" src="https://esham.io/images/me@2x.jpg"  alt="Benjamin Esham trying out all the stuff and just as confused as the rest of us."  title="trying out all the stuff and just as confused as the rest of us." /> Benjamin Esham</a> <span class="p-note"> trying out all the stuff and just as confused as the rest of us.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https:/jkphl.is/" title="web architect and designer from Nuremberg, Germany.">Joschi Kuphal</a> <span class="p-note"> web architect and designer from Nuremberg, Germany</span></li>

  </ul>