<h2 id="openpedagogy">Open Pedagogy</h2>
  <ul class="follow">
    <li class="h-card p-follow-of"><a class="p-name u-url" href="https://jrdingwall.ca/blogwall/" rel="colleague"><img class="u-photo" src="https://jrdingwall.ca/wp-content/uploads/2018/05/10154625899945836.jpg">JR Dingwall</a><span class="p-note"> Reclaiming my digital life
</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="https://disruptivepedagogy.ca/" rel="colleague"><img class="u-photo" src="https://disruptivepedagogy.files.wordpress.com/2018/12/mel-young-head-shot-smallest-2.jpg">Mel Young</a><span class="p-note"> Disruptive Pedagogy
</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="http://www.musicmatters405.com/" rel="colleague"><img class="u-photo" src="http://www.musicmatters405.com/uploads/7/6/4/7/76477675/published/10604397-10152760278275568-2721889622749933163-o.jpg?1548093905">Kathy Essmiller</a><span class="p-note"> create, connect, respond
</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="http://www.musicmatters405.com/" rel="colleague"><img class="u-photo" src="http://www.musicmatters405.com/uploads/7/6/4/7/76477675/published/10604397-10152760278275568-2721889622749933163-o.jpg?1548093905">Kathy Essmiller</a><span class="p-note"> create, connect, respond
</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="http://etap640.edublogs.org/" rel="colleague muse">Alex Pickett</a><span class="p-note"> Sharing What I know Always Learning And
</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="http://www.musicmatters405.com/" rel="colleague"><img class="u-photo" src="http://www.musicmatters405.com/uploads/7/6/4/7/76477675/published/10604397-10152760278275568-2721889622749933163-o.jpg?1548093905">Kathy Essmiller</a><span class="p-note"> create, connect, respond
</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="http://etap640.edublogs.org/" rel="colleague muse">Alex Pickett</a><span class="p-note"> Sharing What I know Always Learning And
</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="http://riftofthemagi.blogspot.com/" rel="colleague muse">George Station</a><span class="p-note"> Rift of the Magi
</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="https://econproph.com/" rel="colleague muse"><img class="u-photo" src="https://i1.wp.com/jimluke.com/wp-content/uploads/2013/01/JimLuke-cropped.jpg">Jim Luke</a><span class="p-note"> Running errands for ideas at the intersections of economics, org theory, higher ed, and open pedagogy.
</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="http://billymeinke.com/"><img class="u-photo" src="http://billymeinke.com/img/billy_armory_max.jpg">Billy Meinke</a><span class="p-note"> technologist that works on open learning environments</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="https://francesbell.com/"><img class="u-photo" src="https://marychaykodotcom.files.wordpress.com/2011/10/france-trip-2010-482.jpg?w=374">Francess Bell</a><span class="p-note"> woman, a friend, a wife, a mother, a grandmother, a sister, an aunt, a cousin, a maker, a gardener, a blogger, an open and itinerant scholar, and a fedwiki fan.</span></li>
     <li class="h-card p-follow-of"><a class="p-name u-url" href="https://marychayko.com/"><img class="u-photo" src="https://marychaykodotcom.files.wordpress.com/2011/10/france-trip-2010-482.jpg?w=374">Mary Chayko</a><span class="p-note">Exploring media, technology, and social connecteness</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="http://www.leighgraveswolf.com/">Leigh Graves Wolf</a><span class="p-note">Educational Technology, Pedagogy, Photography & Food</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="https://jorg.pareigis.se/2/"><img class="u-photo" src="https://jorg.pareigis.se/2/wp-content/uploads/2018/09/joerg_pareigis_blackand-white01_round-600x600.png">J¨ørg Pareigis</a><span class="p-note">Interested and active in service research, open education, people and life in general.</span></li>
    <li class="u-follow-of h-card"><a class="p-name u-url" href="https://jenniferenglund.net/"><img class="u-photo" src="https://i0.wp.com/jenniferenglund.net/wp-content/uploads/2018/12/Jennifer_4181-1.jpg">Jennier Englund</a><span class="p-note">Experiment with new types of technology and connect with others interested in the same topics</span></li>
     <li class="u-follow-of h-card"><a class="p-name u-url" href="https://idevries.com/" rel="colleague ">Irwin Devries</a><span class="p-note">Reflections and ideas on open and distance learning
</span></li>
    <li class="u-follow-of h-card"><a class="p-name u-url" href="https://librariansreed.com/" rel="colleague ">Michelle Reed</a><img class="u-photo" src="https://librariansreed.files.wordpress.com/2019/09/reed_cc_tan.png"><span class="p-note">Librarian. Open advocate. Recovering writer. 
</span></li>
     <li class="u-follow-of h-card"><a class="p-name u-url" href="http://radiogirlradiogirl.blogspot.com/"><img class="u-photo" src="https://pbs.twimg.com/profile_images/3368135262/a01dafffd3f21df8031ba83389da035c_400x400.jpeg">Kim Fox</a><span class="p-note">TJournalism Prof, Am Univ in Cairo @AUC in @JRMCAUC</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="https://magsamond.com/"><img class="u-photo" src="https://magsamondposts.files.wordpress.com/2013/03/mags.jpg?w=112&zoom=2">Mags Amond</a><span class="p-note">Teacher of Science, Biology & Computer Science</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="https://jarche.com/">Harold Jarche</a><span class="p-note">Tactionable insights on learning & work</span></li>
    <li class="h-card p-follow-of"><a class="p-name u-url" href="https://www.raynamharris.com/blog/"><img class="u-photo" src="https://avatars2.githubusercontent.com/u/7544197?v=4">Rayna Harris</a><span class="p-note">working on community engagement for the Data Commons Pilot Phase Consortium</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://bavatuesdays.com"><img class="u-photo" src="https://farm4.static.flickr.com/3340/3520162738_69d454963c_m.jpg"  alt=""  /> Jim Groom</a><span class="p-note">Edupunk Wordpress phreak</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://cogdogblog.com/" title="This where the dog barks"><img class="u-photo" src="http://cogdogblog.com/wp-content/uploads/2016/06/felix-icon-200-3.png"  alt="" /> CogDog AKA Alan Levine</a> <span class="p-note"> This where the dog barks</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://andheblogs.andyrush.net/"><img class="u-photo" src="https://secure.gravatar.com/avatar/333328e5482a550af32a0db2b763b695?s=192&amp;d=mm&amp;r=g"  alt="Andy Rush "  /> Andy Rush</a><span clas="p-note"></span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://theory.cribchronicles.com/">Bonnie Stewart</a><span clas="p-note"></span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://wiobyrne.com/" title="partner in crime"><img class="u-photo" src="https://i2.wp.com/c2.staticflickr.com/8/7322/15928928423_e401b37f87_o.jpg?w=740&amp;ssl=1"  alt=""  title="partner in crime" /> Ian O&#039;Byrne</a> <span class="p-note"> partner in crime</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://blog.mahabali.me/" title="Friend and leader, founder of virtually connecting"><img class="u-photo" src="https://balimaha.files.wordpress.com/2013/10/30108_389802611563_1857305_n.jpg"  alt=""  title="Friend and leader, founder of virtually connecting" /> Maha Bali</a> <span class="p-note"> Friend and leader, founder of virtually connecting</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://infocult.typepad.com/" title="Digital Storyteller, open pedagogy">Bryan Alexander</a> <span class="p-note"> Digital Storyteller, open pedagogy</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://infocult.typepad.com/" title="Digital Storyteller, open pedagogy"><img class="u-photo" src="http://infocult.typepad.com/.a/6a00d83451b88a69e200e54ff2c7368833-150wi"  alt="" /> Bryan Alexander</a> <span class="p-note"> Digital Storyteller, open pedagogy</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://darcynorman.net/" title="manager of the Learning Technologies group in the Taylor Institute for Teaching and Learning,">Darcy Norman</a> <span class="p-note"> manager of the Learning Technologies group in the Taylor Institute for Teaching and Learning,</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://www.gardnercampbell.net/blog1/" title="Open Pedagogy hero"><img class="u-photo" src="http://www.gardnercampbell.net/blog1/wp-content/uploads/2012/02/cropped-kubrickheader-custom.jpg"  alt="Garner Campbell Open Pedagogy hero"  title="Open Pedagogy hero" /> Garner Campbell</a> <span class="p-note"> Open Pedagogy hero</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://sites.google.com/site/verenanz/" title="always looking for new opportunities to help change the way we are &#8220;doing things&#8221; in Education."><img class="u-photo" src="https://sites.google.com/site/verenanz/_/rsrc/1393817832678/Home/v_picture.jpg?height=150&amp;width=200"  alt=""  title="always looking for new opportunities to help change the way we are &#8220;doing things&#8221; in Education." /> Verena Roberts</a> <span class="p-note"> always looking for new opportunities to help change the way we are &#8220;doing things&#8221; in Education.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://silenceandvoice.com/" title="Director of Training &amp; Knowledge Management + Educational Researcher + Professor + Poet + Wikipedian = Liminality + Actor-Network Theory + Open Education"><img class="u-photo" src="http://2.gravatar.com/avatar/bccab3593f46edbef46ca982cc0916a7?s=98&amp;d=monsterid&amp;r=r"  alt="" /> Jeffery Keefer</a> <span class="p-note"> Director of Training &amp; Knowledge Management + Educational Researcher + Professor + Poet + Wikipedian = Liminality + Actor-Network Theory + Open Education</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://remikalir.com/blog" title="remi(x)learning ">Remi Kalir</a> <span class="p-note"> remi(x)learning </span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://robinderosa.net/" title="Open Education and Higher Education">Robin DeRosa</a> <span class="p-note"> Open Education and Higher Education</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://catherinecronin.net/" title="open educator, open researcher and educational developer in CELT">Catherine Cronin</a> <span class="p-note"> open educator, open researcher and educational developer in CELT</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://tachesdesens.blogspot.com/" title="edupunk language teacher "><img class="u-photo" src="http://lh3.googleusercontent.com/-cOKhxEc3pds/AAAAAAAAAAI/AAAAAAAApCA/vM4FqWPQV5U/s80-c/photo.jpg"  alt=""  title="edupunk language teacher " /> Simon Esnor</a> <span class="p-note"> edupunk language teacher </span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://autummcaines.com/" title="The Aumtumm with two m&#8217;s">Autumm Caines</a> <span class="p-note"> The Aumtumm with two m&#8217;s</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://dougbelshaw.com/blog/start/" title="Gotta badge for that?">Doug Belshaw</a> <span class="p-note"> Gotta badge for that?</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://www.laurahilliger.com/" title="An intellectual multipod. I’m a lot of things."><img class="u-photo" src="https://www.laurahilliger.com/wp-content/uploads/2011/02/sq-profile-bout-small.jpg"  alt=""  title="An intellectual multipod. I’m a lot of things." /> Laura Hilliger</a> <span class="p-note"> An intellectual multipod. I’m a lot of things.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://debbaffled.wordpress.com/" title="Passionate about Open Educational Practice, Open Digital Badges and Online Learning">Deb Baff</a> <span class="p-note"> Passionate about Open Educational Practice, Open Digital Badges and Online Learning</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://clarissasorensenunruh.com/" title="Teaching chemisty through social media">Clarissa Sorensen-Unruh</a> <span class="p-note"> Teaching chemisty through social media</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://amynelson.net/" title="Associate Professor of History at Virginia Tech, where I teach Soviet history and culture, animal studies, and contemporary pedagogy.">Amy Nelson</a> <span class="p-note"> Associate Professor of History at Virginia Tech, where I teach Soviet history and culture, animal studies, and contemporary pedagogy.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://www.oliverquinlan.com/blog/" title="Senior Research Manager at The Raspberry Pi Foundation, leading the foundation’s research into learning and teaching in digital making and computing">Oliver Quinlan</a> <span class="p-note"> Senior Research Manager at The Raspberry Pi Foundation, leading the foundation’s research into learning and teaching in digital making and computing</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="https://labrumfield.com/" title="Account Manager at Reclaim Hosting. She has a BA in Creative Writing from the University of Mary Washington."><img class="u-photo" src="https://labrumfield.com/wp-content/uploads/2018/03/lauren-1.png"  alt=""  title="Account Manager at Reclaim Hosting. She has a BA in Creative Writing from the University of Mary Washington." /> Lauren Brumfield</a> <span class="p-note"> Account Manager at Reclaim Hosting. She has a BA in Creative Writing from the University of Mary Washington.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://www.runeman.org/" title="36 years as teacher and computer director for the King Philip Regional School District in southeastern Massachusetts, USA.">Algot Runeman</a> <span class="p-note"> 36 years as teacher and computer director for the King Philip Regional School District in southeastern Massachusetts, USA.</span></li>
<li class="h-card p-follow-of"><a class="p-name  u-url" href="http://marendeepwell.com/" title="CEO @A_L_T #altc | Anthropologist | Open Practitioner | "><img class="u-photo" src="http://marendeepwell.com/wp-content/uploads/2018/02/MDeepwell_2017-300x300.jpg"  alt="Maren Deepwell CEO @A_L_T #altc | Anthropologist | Open Practitioner | "  title="CEO @A_L_T #altc | Anthropologist | Open Practitioner | " /> Maren Deepwell</a> <span class="p-note"> CEO @A_L_T #altc | Anthropologist | Open Practitioner | </span></li>
    <li class="h-card p-follow-of"><a class="p-name  u-url" href="https://brainstorminprogress.com" title="focusing on online course design that promotes student success and retention, and faculty development">Geoff Cain</a> <span class="p-note"> focusing on online course design that promotes student success and retention, and faculty developmentsoutheastern Massachusetts, USA.</span></li>
 <li class="h-card p-follow-of"><a class="p-name  u-url" href="https://x28newblog.wordpress.com" ><span class="p-name"> Matthias Melcher</span></a> <span class="p-note"> Since the early gopher days, I have drifted more and more towards content</span></li>

  </ul>