<?php
require dirname(__DIR__).'/library.php';
$id = $_GET['id'] ?? '';
if (!is_string($id) || !preg_match('/^[a-f0-9]{28,32}$/D', $id)) {
    http_response_code(404); exit('Post not found.');
}
$file = __DIR__.'/posts/'.substr($id,0,2).'/'.$id.'.json';
if (!is_file($file)) { http_response_code(404); exit('Post not found.'); }
$post = json_decode(file_get_contents($file), true);
if (!is_array($post) || ($post['access'] ?? '') !== 'PUBLIC' || ($post['publish_status'] ?? '') !== 'published') {
    http_response_code(404); exit('Post not found.');
}
header('Content-Type: text/html; charset=utf-8');
header('X-Content-Type-Options: nosniff');
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?=esc($post['title'])?> · Greg McVerry</title>
<link rel="canonical" href="<?=esc('https://jgregorymcverry.com'.$post['url'])?>">
<link rel="stylesheet" href="/reset.css"><link rel="stylesheet" href="/styles.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Heebo|Quicksand&amp;display=swap">
<link rel="stylesheet" href="/archive/archive.css"><link rel="stylesheet" href="/archive/known/post.css">
<link rel="alternate" type="application/rss+xml" href="/archive/feed.php" title="All posts">
</head><body><a class="skip-link" href="#post">Skip to post</a>
<?php include dirname(__DIR__,2).'/header.php'; ?></header>
<main class="archive-shell" id="post"><p><a href="/archive/">← Post archive</a></p>
<article class="archive-entry h-entry"><div class="entry-meta"><a href="<?=esc('/archive/?type='.$post['type'])?>" class="post-type"><?=esc(archive_types()[$post['type']] ?? 'Post')?></a><time class="dt-published" datetime="<?=esc($post['published'])?>"><?=esc($post['display_date'])?></time></div>
<p class="p-name e-content"><?=esc($post['title'])?></p>
<?php foreach ($post['reply_urls'] as $url): ?><p class="reply-context">In reply to <a class="u-in-reply-to" href="<?=esc($url)?>"><?=esc($url)?></a></p><?php endforeach; ?>
<?php // body_html is generated by the offline HTML allowlist sanitizer, never copied raw from Known. ?>
<div class="e-content"><?=$post['body_html']?></div>
<?php if ($post['tags']): ?><p class="post-tags"><?php foreach($post['tags'] as $tag): ?><span class="p-category">#<?=esc($tag)?></span> <?php endforeach; ?></p><?php endif; ?>
<p class="provenance">By <a class="p-author h-card" href="/">Greg McVerry</a> · <a class="u-url" href="<?=esc($post['url'])?>">Permalink</a> · <a href="<?=esc($post['original_url'])?>">Original Known URL</a></p>
</article></main><div class="archive-footer"><?php include dirname(__DIR__,2).'/footer.php'; ?></div></body></html>
